3 module
js-tasks-ru/nodejs-20210907_anton1922 pull request #6
Opened 2021-09-21 09:48 UTC by Anton1922

Added solutions for tasks 2 and 3

2021-09-21 09:49 UTC, jsru commented
Добавляю преподавателя (@tadjik1) для код-ревью.

2021-09-24 09:21 UTC, tadjik1 commented on 03-streams/03-file-server-get/server.js
> +        encoding: 'utf8',
тут кодировка не нужна, т.к. файл может быть любой - и картинка, например, и видео. мы читать его должны просто как набор байт и отдавать тоже.

2021-09-24 09:21 UTC, tadjik1 requested changes
@Anton1922 в целом хорошее решение, но небольшой нюанс с кодировкой стоит поправить

2021-09-26 22:21 UTC, Anton1922 commented on 03-streams/03-file-server-get/server.js
> +        encoding: 'utf8',
Понял. Исправил)

2021-09-27 04:21 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-09-27 13:39 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-09-28 08:01 UTC, tadjik1 commented on 03-streams/04-file-server-post/server.js
> +          writeStream.end(() => {
@Anton1922 пересмотрите, пожалуйста, видео нашего последнего занятия - я рассказывал там как обрабатываются ситуации превышения лимита (и ошибки в `limitSizeStream`)

2021-09-28 08:03 UTC, tadjik1 requested changes
оставил небольшой комментарий касающийся завершения работы стрима

2021-09-28 12:26 UTC, Anton1922 commented on 03-streams/04-file-server-post/server.js
> +          writeStream.end(() => {
Понял. Я пытался сделать без помощи прошлого видео, не смотрел специально начало)) Посмотрю тогда и исправлю. Спасибо за обратную связь!

2021-10-04 23:10 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-10-04 23:56 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-10-05 10:21 UTC, jsru commented
Добавляю преподавателя (@tadjik1) для код-ревью.

2021-10-05 10:33 UTC, tadjik1 approved these changes
@Anton1922 все отлично! падающий тест это была проблема ноды, я в слаке вам написал подробнее причины

2021-10-05 10:33 UTC, merged